[package]
name = "mermaid-cli-rs"
version = "0.3.0"
edition = "2021"
authors = ["0x6b"]
description = "Convert Mermaid diagram to PNG or SVG format."
license-file = "LICENSE"
build = "build.rs"

[[bin]]
name = "mmdc"
path = "src/main.rs"

[dependencies]
axum = "0.7.3"
camino = "1.1.6"
clap = { version = "4.4.12", features = ["derive"] }
headless_chrome = { version = "1.0.8", features = ["fetch"] }
mime = "0.3.17"
tokio = { version = "1.35.1", features = ["full"] }

[build-dependencies]
reqwest = { version = "0.11.23", features = ["blocking"] }

[profile.release]
codegen-units = 1
lto = true
strip = true
