[package]
name = "mermaid-cli-rs"
version = "0.1.0"
edition = "2021"
authors = ["0x6b"]
description = "Convert Mermaid diagram to PNG or SVG format."
license-file = "LICENSE"
build = "build.rs"

[[bin]]
name = "mmdc"
path = "src/main.rs"

[dependencies]
axum = "0.6.7"
camino = "1.0.7"
headless_chrome = { version = "1.0.5", features = ["fetch"] }
mime = "0.3.16"
structopt = { version = "0.3.26", default_features = false, features = ["doc"] }
tokio = { version = "1.17.0", features = ["full"] }

[build-dependencies]
reqwest = { version = "0.11.10", features = ["blocking"] }

[profile.release]
codegen-units = 1
lto = true
strip = true
