# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
chain_width = 70
comment_width = 100
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
max_width = 100
merge_derives = false
struct_lit_width = 50
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true
